config/routes.rb
Rails.application.routes.draw do

  resources :gold_reports do
    member do
      post 'preapprove'
      post 'approve'
      post 'reject'
    end
  end

  resources :seal_codes

  resources :branches


  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :seal_codes, class_name: "Branch", foreign_key: "from_branch"
  has_many :seal_codes, class_name: "Branch", foreign_key: "to_branch"
end

def namecode;
  " #{code} #{name}";
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:code, :name, :telephone)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.haml
= form_for @branch do |f|
  - if @branch.errors.any?
    #error_explanation
      %h2= "#{pluralize(@branch.errors.count, "error")} prohibited this branch from being saved:"
      %ul
        - @branch.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :code
    = f.text_field :code, class: 'form-control'
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :telephone
    = f.text_field :telephone, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-default'

app/views/branches/edit.html.haml
%h1 Editar información de sucursal

= render 'form'

= link_to 'Show', @branch
\|
= link_to 'Back', branches_path

app/views/branches/index.html.haml
%h1 Sucursales

%table.table.table-striped
  %thead
    %tr
      %th Code
      %th Name
      %th Telephone
      %th
      %th
      %th

  %tbody
    - @branches.each do |branch|
      %tr
        %td= branch.code
        %td= branch.name
        %td= branch.telephone
        %td= link_to 'Show', branch
        %td= link_to 'Edit', edit_branch_path(branch)
        %td= link_to 'Destroy', branch, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Introducir Sucursal', new_branch_path

app/views/branches/new.html.haml
%h1 Introducir una Sucursal

= render 'form'

= link_to 'Back', branches_path

app/views/branches/show.html.haml
%p#notice= notice

%p
  %b Code:
  = @branch.code
%p
  %b Name:
  = @branch.name
%p
  %b Telephone:
  = @branch.telephone

= link_to 'Edit', edit_branch_path(@branch)
\|
= link_to 'Back', branches_path