config/routes.rb
Rails.application.routes.draw do

  resources :gold_reports do
    member do
      post 'preapprove'
      post 'approve'
      post 'reject'
    end
  end

  resources :seal_codes

  resources :branches


  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/seal_code.rb
class SealCode < ActiveRecord::Base
  belongs_to :branch, foreign_key: "from_branch"
  belongs_to :branch, foreign_key: "to_branch"
  belongs_to :goldreport

end

app/controllers/seal_codes_controller.rb
class SealCodesController < ApplicationController
  before_action :set_seal_code, only: [:show, :edit, :update, :destroy]

  # GET /seal_codes
  # GET /seal_codes.json
  def index
    @seal_codes = SealCode.all
    @branch = Branch.all
  end

  # GET /seal_codes/1
  # GET /seal_codes/1.json
  def show
    @branch = Branch.all
  end

  # GET /seal_codes/new
  def new
    @seal_code = SealCode.new
  end

  # GET /seal_codes/1/edit
  def edit

  end

  # POST /seal_codes
  # POST /seal_codes.json
  def create
    @seal_code = SealCode.new(seal_code_params)

    respond_to do |format|
      if @seal_code.save
        format.html { redirect_to @seal_code, notice: 'Seal code was successfully created.' }
        format.json { render :show, status: :created, location: @seal_code }
      else
        format.html { render :new }
        format.json { render json: @seal_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seal_codes/1
  # PATCH/PUT /seal_codes/1.json
  def update
    respond_to do |format|
      if @seal_code.update(seal_code_params)
        format.html { redirect_to @seal_code, notice: 'Seal code was successfully updated.' }
        format.json { render :show, status: :ok, location: @seal_code }
      else
        format.html { render :edit }
        format.json { render json: @seal_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seal_codes/1
  # DELETE /seal_codes/1.json
  def destroy
    @seal_code.destroy
    respond_to do |format|
      format.html { redirect_to seal_codes_url, notice: 'Seal code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seal_code
      @seal_code = SealCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seal_code_params
      params.require(:seal_code).permit(:from_branch, :to_branch, :date, :barcode, :received_by, :supposely_contains, :goldreport_id)
    end
end

app/helpers/seal_codes_helper.rb
module SealCodesHelper
end

app/views/seal_codes/_form.html.haml
= form_for @seal_code do |f|
  - if @seal_code.errors.any?
    #error_explanation
      %h2= "#{pluralize(@seal_code.errors.count, "error")} prohibited this seal_code from being saved:"
      %ul
        - @seal_code.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :from_branch, "Enviado desde"
    - preselected_value = (@seal_code.from_branch.present?) ? @seal_code.from_branch : nil
    - opts = options_from_collection_for_select(Branch.all.order(:code), :id, :namecode, preselected_value)
    = f.select :from_branch, opts, {:include_blank => true}
  .field
    = f.label :to_branch, "Recibido en"
    - preselected_value = (@seal_code.to_branch.present?) ? @seal_code.to_branch : nil
    - opts = options_from_collection_for_select(Branch.all.order(:code), :id, :namecode, preselected_value)
    = f.select :to_branch, opts, {:include_blank => true}
  .field
    = f.label :date
    = f.datetime_select :date
  .field
    = f.label :barcode
    = f.text_field :barcode
  .field
    = f.label :received_by
    = f.text_field :received_by
  .field
    = f.label :supposely_contains
    = f.number_field :supposely_contains
  .field
    = f.label :goldreport
    = f.text_field :goldreport
  .actions
    = f.submit 'Save'

app/views/seal_codes/edit.html.haml
%h1 Editing seal_code

= render 'form'

= link_to 'Show', @seal_code
\|
= link_to 'Back', seal_codes_path

app/views/seal_codes/index.html.haml
%h1 Listing seal_codes

%table.table.table-striped
  %thead
    %tr
      %th From branch
      %th To branch
      %th Date
      %th Barcode
      %th Received by
      %th Supposely contains
      %th Goldreport
      %th
      %th
      %th

  %tbody
    - @seal_codes.each do |seal_code|
      %tr
        %td= @branch.find(seal_code.from_branch).name if seal_code.from_branch?
        %td= @branch.find(seal_code.to_branch).name if seal_code.to_branch?
        %td= seal_code.date
        %td= seal_code.barcode
        %td= seal_code.received_by
        %td= seal_code.supposely_contains
        %td= seal_code.goldreport
        %td= link_to 'Show', seal_code
        %td= link_to 'Edit', edit_seal_code_path(seal_code)
        %td= link_to 'Destroy', seal_code, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Seal code', new_seal_code_path

app/views/seal_codes/new.html.haml
%h1 New seal_code

= render 'form'

= link_to 'Back', seal_codes_path

app/views/seal_codes/show.html.haml
%p#notice= notice

%p
  %b From branch:
  = @branch.find(@seal_code.from_branch).name if @seal_code.from_branch?
%p
  %b To branch:
  = @branch.find(@seal_code.to_branch).name if @seal_code.to_branch?
%p
  %b Date:
  = @seal_code.date
%p
  %b Barcode:
  = @seal_code.barcode
%p
  %b Received by:
  = @seal_code.received_by
%p
  %b Supposely contains:
  = @seal_code.supposely_contains
%p
  %b Goldreport:
  = @seal_code.goldreport

= link_to 'Edit', edit_seal_code_path(@seal_code)
\|
= link_to 'Back', seal_codes_path