config/routes.rb
Rails.application.routes.draw do

  resources :gold_reports do
    member do
      post 'preapprove'
      post 'approve'
      post 'reject'
    end
  end

  resources :seal_codes

  resources :branches


  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/gold_report.rb
class GoldReport < ActiveRecord::Base
  belongs_to :branch
  belongs_to :assistants
  has_many :seal_codes

  include AASM
  aasm do
    state :draft, :initial => true
    state :preapproved
    state :approved

    event :preapprove do
       transitions :from => :draft, :to => :preapproved
    end
    event :approve do
       transitions :from => :preapproved, :to => :approved
    end
    event :reject do
       transitions :from => :preapproved, :to => :draft
    end
  end

end

app/controllers/gold_reports_controller.rb
class GoldReportsController < ApplicationController
  before_action :set_gold_report, only: [:show, :edit, :update, :destroy]


  # GET /gold_reports
  # GET /gold_reports.json
  def index
    @gold_reports = GoldReport.all
  end

  # GET /gold_reports/1
  # GET /gold_reports/1.json
  def show
  end

  # GET /gold_reports/new
  def new
    @gold_report = GoldReport.new
  end

  # GET /gold_reports/1/edit
  def edit
  end

  def preapprove
    @gold_report = GoldReport.find(params[:id])
    @gold_report.preapprove!
    return redirect_to gold_reports_path
  end

  def approve
    @gold_report = GoldReport.find(params[:id])
    @gold_report.approve!
    return redirect_to gold_reports_path
  end

  def reject
    @gold_report = GoldReport.find(params[:id])
    @gold_report.reject!
    return redirect_to gold_reports_path
  end

  # POST /gold_reports
  # POST /gold_reports.json
  def create
    @gold_report = GoldReport.new(gold_report_params)

    respond_to do |format|
      if @gold_report.save
        format.html { redirect_to @gold_report, notice: 'Gold report was successfully created.' }
        format.json { render :show, status: :created, location: @gold_report }
      else
        format.html { render :new }
        format.json { render json: @gold_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gold_reports/1
  # PATCH/PUT /gold_reports/1.json
  def update
    respond_to do |format|
      if @gold_report.update(gold_report_params)
        format.html { redirect_to @gold_report, notice: 'Gold report was successfully updated.' }
        format.json { render :show, status: :ok, location: @gold_report }
      else
        format.html { render :edit }
        format.json { render json: @gold_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gold_reports/1
  # DELETE /gold_reports/1.json
  def destroy
    @gold_report.destroy
    respond_to do |format|
      format.html { redirect_to gold_reports_url, notice: 'Gold report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gold_report
      @gold_report = GoldReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gold_report_params
      params.require(:gold_report).permit(:end_date, :branch_id, :assistants_id, :pawned_capital, :bought_capital, :export_real_weight, :container_qty, :pawns_listed_total_weight, :pawns_10k_weight, :pawns_14k_weight, :pawns_18k_weight, :pawns_with_diamonds_weight, :pawns_saved_weight, :pawns_stone_weight, :pawns_other_weight, :bought_listed_total_weight, :bought_10k_weight, :bought_14k_weight, :bought_18k_weight, :bought_with_diamonds_weight, :bought_saved_weight, :bought_stone_weight, :bought_other_weight, :comments, :ayudantes, :seal_code_ids => [])
    end
end

app/helpers/gold_reports_helper.rb
module GoldReportsHelper
end

app/views/gold_reports/_form.html.haml
= form_for @gold_report do |f|
  - if @gold_report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gold_report.errors.count, "error")} prohibited this gold_report from being saved:"
      %ul
        - @gold_report.errors.full_messages.each do |msg|
          %li= msg
  .panel.panel-default
    .panel-heading
      %h3 Información General
    .panel-body
      .row
        .form-group.col-md-4
          = f.label :end_date
          = f.date_select :end_date,{:class => "form-control"}
        .form-group.col-md-3
          = f.label :branch
          - opts = options_from_collection_for_select(Branch.all.order(:code), :id, :namecode)
          = f.select :branch_id, opts, {:include_blank => true}, class: 'form-control'
        .form-group.col-md-2
          = f.label :container_qty
          = f.text_field :container_qty, class: 'form-control'
        .form-group.col-md-4
          = f.label :ayudantes
          = f.text_area :ayudantes, class: 'form-control'
        .form-group.col-md-4
          = f.label :seal_codes
          - opts = options_from_collection_for_select(SealCode.all.order(:barcode), :id, :barcode)
          = f.select :seal_code_ids, opts, {:include_blank => true} ,{multiple: true, placeholder: 'Seleccione ', class: 'form-control'}
  .panel.panel-default
    .panel-heading
      %h3 Información de Listados
    .panel-body
      .row
        .form-group.col-md-3
          = f.label :pawned_capital
          = f.text_field :pawned_capital, class: 'form-control'
        .form-group.col-md-3
          = f.label :bought_capital, "Capital Comprado"
          = f.text_field :bought_capital, class: 'form-control'
        .form-group.col-md-3
          = f.label :export_real_weight, "Peso Exportado (g)"
          = f.text_field :export_real_weight,class: 'form-control'
  .panel.panel-default
    .panel-heading
      %h3 Información de Empeños
    .panel-body
      .row
        .form-group.col-md-4
          = f.label :pawns_listed_total_weight
          = f.text_field :pawns_listed_total_weight, class: 'form-control'
      .row
        .form-group.col-md-3
          = f.label :pawns_10k_weight
          = f.text_field :pawns_10k_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :pawns_14k_weight
          = f.text_field :pawns_14k_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :pawns_18k_weight
          = f.text_field :pawns_18k_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :pawns_with_diamonds_weight
          = f.text_field :pawns_with_diamonds_weight, class: 'form-control'
      .row
        .form-group.col-md-3
          = f.label :pawns_saved_weight
          = f.text_field :pawns_saved_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :pawns_stone_weight
          = f.text_field :pawns_stone_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :pawns_other_weight
          = f.text_field :pawns_other_weight, class: 'form-control'
  .panel.panel-default
    .panel-heading
      %h3 Información de Compras
    .panel-body
      .row
        .form-group.col-md-4
          = f.label :bought_listed_total_weight
          = f.text_field :bought_listed_total_weight, class: 'form-control'
      .row
        .form-group.col-md-3
          = f.label :bought_10k_weight
          = f.text_field :bought_10k_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :bought_14k_weight
          = f.text_field :bought_14k_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :bought_18k_weight
          = f.text_field :bought_18k_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :bought_with_diamonds_weight
          = f.text_field :bought_with_diamonds_weight, class: 'form-control'
      .row
        .form-group.col-md-3
          = f.label :bought_saved_weight
          = f.text_field :bought_saved_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :bought_stone_weight
          = f.text_field :bought_stone_weight, class: 'form-control'
        .form-group.col-md-3
          = f.label :bought_other_weight
          = f.text_field :bought_other_weight, class: 'form-control'
  .form-group
    = f.label :comments
    = f.text_area :comments, class: 'form-control'
  .actions
    = f.submit 'Save Draft', class: 'btn btn-default'

app/views/gold_reports/_form_bought_gold.html.haml
/ Modal
#comprasModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h4#myModalLabel.modal-title Empeños de Sucursal
      .modal-body
        = form_for @gold_report do |f|
          - if @gold_report.errors.any?
            #error_explanation
              %h2= "#{pluralize(@gold_report.errors.count, "error")} prohibited this gold_report from being saved:"
              %ul
                - @gold_report.errors.full_messages.each do |msg|
                  %li= msg
          .field
            = f.label :bought_capital
            = f.number_field :bought_capital
          .field
            = f.label :container_qty
            = f.number_field :container_qty
          .field
            = f.label :export_real_weight
            = f.number_field :export_real_weight
          .field
            = f.label :pawns_listed_total_weight
            = f.number_field :pawns_listed_total_weight
          .field
            = f.label :pawns_10k_weight
            = f.number_field :pawns_10k_weight
          .field
            = f.label :pawns_14k_weight
            = f.number_field :pawns_14k_weight
          .field
            = f.label :pawns_18k_weight
            = f.number_field :pawns_18k_weight
          .field
            = f.label :pawns_with_diamonds_weight
            = f.number_field :pawns_with_diamonds_weight
          .field
            = f.label :pawns_saved_weight
            = f.number_field :pawns_saved_weight
          .field
            = f.label :pawns_stone_weight
            = f.number_field :pawns_stone_weight
          .field
            = f.label :pawns_other_weight
            = f.number_field :pawns_other_weight
          .actions
            = f.submit 'Save'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary{:type => "button"} Save changes

app/views/gold_reports/_form_pawn_gold.html.haml
/ Modal
#empenosModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h4#myModalLabel.modal-title Empeños de Sucursal
      .modal-body
        = form_for @gold_report do |f|
          - if @gold_report.errors.any?
            #error_explanation
              %h2= "#{pluralize(@gold_report.errors.count, "error")} prohibited this gold_report from being saved:"
              %ul
                - @gold_report.errors.full_messages.each do |msg|
                  %li= msg
          .field
            = f.label :pawned_capital
            = f.number_field :pawned_capital
          .field
            = f.label :container_qty
            = f.number_field :container_qty
          .field
            = f.label :export_real_weight
            = f.number_field :export_real_weight
          .field
            = f.label :pawns_listed_total_weight
            = f.number_field :pawns_listed_total_weight
          .field
            = f.label :pawns_10k_weight
            = f.number_field :pawns_10k_weight
          .field
            = f.label :pawns_14k_weight
            = f.number_field :pawns_14k_weight
          .field
            = f.label :pawns_18k_weight
            = f.number_field :pawns_18k_weight
          .field
            = f.label :pawns_with_diamonds_weight
            = f.number_field :pawns_with_diamonds_weight
          .field
            = f.label :pawns_saved_weight
            = f.number_field :pawns_saved_weight
          .field
            = f.label :pawns_stone_weight
            = f.number_field :pawns_stone_weight
          .field
            = f.label :pawns_other_weight
            = f.number_field :pawns_other_weight
          .actions
            = f.submit 'Save'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary{:type => "button"} Save changes

app/views/gold_reports/edit.html.haml
%h1 Editar Reporte de Oro

= render 'form'


= button_to "Send for Approval", {:action => "preapprove" }, {:class => "btn-default btn" }
= button_to "Reject", {:action => "reject" }, {:class => "btn-default btn" }
= button_to "Approve", {:action => "approve" }, {:class => "btn-default btn" }


= link_to 'Show', @gold_report
\|
= link_to 'Back', gold_reports_path

app/views/gold_reports/index.html.haml
%h1 Reportes de Oro

%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Fecha
      %th Sucursal
      %th Capital Empeñado
      %th Capital Comprado
      %th Peso Exportado (g)
      %th Estado
      %th
      %th
      %th

  %tbody
    - @gold_reports.each do |gold_report|
      %tr
        %td= gold_report.id
        %td= gold_report.end_date
        %td= gold_report.branch.name if gold_report.branch_id?
        %td= gold_report.pawned_capital
        %td= gold_report.bought_capital
        %td= gold_report.export_real_weight
        %td= gold_report.aasm_state
        %td= link_to 'Show', gold_report
        %td= link_to 'Edit', edit_gold_report_path(gold_report)
        %td= link_to 'Destroy', gold_report, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Gold report', new_gold_report_path

app/views/gold_reports/new.html.haml
%h1 Formulario de Reporte de Oro

= render 'form'

= link_to 'Back', gold_reports_path

app/views/gold_reports/show.html.haml
%p#notice= notice
.panel.panel-default
  .panel-heading
    %h3 Información de General
  .panel-body
    %p
      %b End date:
      = @gold_report.end_date
    %p
      %b Branch:
      = @gold_report.branch.name if @gold_report.branch_id?
    %p
      %b Assistants:
      = @gold_report.ayudantes
    %p
      %b Seal Codes:
      = @gold_report.seal_codes.map{|e| e.barcode}.join('/')
.panel.panel-default
  .panel-heading
    %h3 Información de Listados
  .panel-body
    %p
      %b Pawned capital:
      = @gold_report.pawned_capital
    %p
      %b Bought capital:
      = @gold_report.bought_capital
    %p
      %b Export real weight:
      = @gold_report.export_real_weight
    %p
      %b Container qty:
      = @gold_report.container_qty
.panel.panel-default
  .panel-heading
    %h3 Información de Empeños
  .panel-body
    %p
      %b Pawns listed total weight:
      = @gold_report.pawns_listed_total_weight
    %p
      %b Pawns 10k weight:
      = @gold_report.pawns_10k_weight
    %p
      %b Pawns 14k weight:
      = @gold_report.pawns_14k_weight
    %p
      %b Pawns 18k weight:
      = @gold_report.pawns_18k_weight
    %p
      %b Pawns with diamonds weight:
      = @gold_report.pawns_with_diamonds_weight
    %p
      %b Pawns saved weight:
      = @gold_report.pawns_saved_weight
    %p
      %b Pawns stone weight:
      = @gold_report.pawns_stone_weight
    %p
      %b Pawns other weight:
      = @gold_report.pawns_other_weight
.panel.panel-default
  .panel-heading
    %h3 Información de Compras
  .panel-body
    %p
      %b Bought listed total weight:
      = @gold_report.bought_listed_total_weight
    %p
      %b Bought 10k weight:
      = @gold_report.bought_10k_weight
    %p
      %b Bought 14k weight:
      = @gold_report.bought_14k_weight
    %p
      %b Bought 18k weight:
      = @gold_report.bought_18k_weight
    %p
      %b Bought with diamonds weight:
      = @gold_report.bought_with_diamonds_weight
    %p
      %b Bought saved weight:
      = @gold_report.bought_saved_weight
    %p
      %b Bought stone weight:
      = @gold_report.bought_stone_weight
    %p
      %b Bought other weigth:
      = @gold_report.bought_other_weight
%p
  %b Comments:
  = @gold_report.comments

= button_to "Send for Approval", {:action => "preapprove" }, {:class => "btn-default btn" }
= button_to "Rechazar", {:action => "reject" }, {:class => "btn-default btn" }
= button_to "Aprobar", {:action => "approve" }, {:class => "btn-default btn" }


= link_to 'Edit', edit_gold_report_path(@gold_report)
\|
= link_to 'Back', gold_reports_path